### ISSUE TITLE
Mechanism to enable all / disable all checks 

### ISSUE THREAD

**Issue by rdubrock** [grafana/synthetic-monitoring-app#158]
We should have something in the UI that allows folks to enable/disable all their checks with a toggle/button/some sort of UI control.

**Comment by mem** [comment]
This is the "tenant enable / disable" functionality. The API is a little wonky right now: you can use the tenant update entry point and set "status" to 0 for active (had to make it so so that all existing tenants remained active), and 1 for inactive. In the future we could add other values, that's why it's not true / false.

**Comment by rdubrock** [comment]
This has been implemented
