### ISSUE TITLE
Add variables and simple functions (eg random) to Request body field

### ISSUE THREAD

**Issue by MurzNN** [grafana/synthetic-monitoring-app#317]
**What would you like to be added**:
Add variables and simple functions (eg random) to Request body field

**Why is this needed**:
Very often we need to check not the static query, but add some dynamics to it. For example, add the random number in GET query of desired range (eg some entity id), to prevent receiving cached queries, or detect the slow ranges of identities.

To solve this task will be good to have ability to insert some variables into Target URL and Request body field, and some way to set value of variable via some function like `randomInRange(1000, 1999)`, `randomFromList([123, 456, 789])`.

What do you think about this idea?

**Comment by MurzNN** [comment]
Also will be good to have ability to randomize frequency a little bit, for example not every 30 seconds, but random number from 25 to 35.

**Comment by mem** [comment]
Adding a query parameter with a different value for every request is already supported in the form of a "cache busting parameter". The use case is exactly that: prevent the server from caching the request. The name of the parameter is specified by the user, and the value is generated each time the check runs. The rationale there is that you might not want to be monitoring the performance of cached queries. Or maybe you do, that's why it's optional.

Adding values to the request body feels like it's a different use case. Note that Synthetic Monitoring provides blackbox _monitoring_ not blackbox _testing_. These are related but different. Could you provide some more details as to what the goal of that would be?

**Comment by MurzNN** [comment]
My use case is checking performance of GraphQL queries, that have multiple
cache levels, so I want to run post queries with different values for
variables (eg entity ids) instead of repeat same query. Now I implemented
this via NewRelic Synthetic test (custom js code), but want to reduce
variety of used tools.

**Comment by MurzNN** [comment]
Our may be you can recommend some other tool for this task from Graphana stack?

**Comment by MurzNN** [comment]
After some consideration I fill the new separate feature request https://github.com/grafana/synthetic-monitoring-app/issues/319 because implementing variables and functions in current interface will be very limited solution.
