### ISSUE TITLE
Synthetic check page duplicated results

### ISSUE THREAD

**Issue by ckbedwell** [grafana/synthetic-monitoring-app#798]
[_Full escalation ticket here._](https://github.com/grafana/support-escalations/issues/10708)

**Summary of Issue**:   
Customer is seeing their checks duplicated multiple times: 
<img width="3089" alt="image" src="https://github.com/grafana/synthetic-monitoring-app/assets/7903188/94a9e6e4-48d9-40f0-bb5b-6c7a25a40bbe">

Even though the check is configured only once
   
This is happening for all of their checks - above is an example of just one.   
   
I believe this is a frontend issue since metric queries seem to be working fine for what I could tell. 
   
Noticed that when I apply a filter, for instance `environment = devNet` then the checks are listed only once as expected.
   
Also noticed that for brand new checks this is not happening, I created a new check in their instance and could see it listed only once - it's been now deleted to not contribute to their billing.

**Comment by peterschretlen** [comment]
It looks like this happens when two checks share the same `job` name.  

I think this is the issue: 
https://github.com/grafana/synthetic-monitoring-app/blob/f4f40b28c490b62153661ff45c90324995246163/src/scenes/Summary/summaryTable.ts#L167-L170

Could we combine `job` and `instance` to make a unique key per check, and then do joinByField on that key?
