### ISSUE TITLE
Browser check creation flow

### ISSUE THREAD

**Issue by peterschretlen** [grafana/synthetic-monitoring-app#863]
How will users create a browser check vs a scripted check? Is it simply a scripted check that includes the browser module in the sample code?

We should nudge users towards using 
```
import { browser } from 'k6/browser'
```

as opposed to the deprecated k6/experimental/browser

**Comment by VikaCep** [comment]
Good point, I think we should add a validation to make sure the script contains that import. 

BTW, currently the checks fail in dev if importing from `k6/browser`, but they pass with `k6/experimental/browser`. Asked @roobre about this earlier today and he mentioned it's because we still need to upgrade to the latest `k6` version. I'm not sure there's a GH for that task but it would be good to keep track about it.

**Comment by Alan01252** [comment]
Although the tests seem to pass I don't think you can actually run them can you? Is that correct?

`Uncaught (in promise) GoError: browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module	at github.com/grafana/xk6-browser/browser.mapBrowser.func7 (native)	at file:///script.k6:20:21(4)
`
I get the error above appear when I try.

Ty!

**Comment by roobre** [comment]
Import `k6/browser` should now be possible.

> I don't think you can actually run them can you? Is that correct?

For now only the Paris location in dev can run them, that will change as we iterate on the approach. The next step will be for all probes in dev to be able to run it, and then we will finally enable this in production.
