### ISSUE TITLE
Unable to get plugin working, returns Something went wrong and 415 Unsupported media type

### ISSUE THREAD

**Issue by BlackDex** [grafana/synthetic-monitoring-app#905]
**What happened**:
Unable to initialize the plugin after fully having it provisioned.
![image](https://github.com/user-attachments/assets/cd51fabb-6445-4524-b056-f96c57bf1be3)
![image](https://github.com/user-attachments/assets/26f6221b-68a5-498f-b5f5-398acfd0192c)

**What you expected to happen**:
The plugin to be initialized and able to add checks.

**How to reproduce it (as minimally and precisely as possible)**:
- Make sure you have a Grafana Cloud account.
- Start a local Grafana docker container which installs this plugin
- Configure the plugin as mentioned in the doc's
- Try to enable it

**Anything else we need to know?**:
This is a clean install, datasource's are accessible and able to retrieve metrics.

**Environment**:
- Grafana version (if running on prem): 11.1.4 (grafana/grafana-enterprise)
- SM plugin version: 1.14.11
- OS Grafana is installed on: docker container
- User OS & Browser: Linux/Firefox & Windows/Edge

**Comment by peterschretlen** [comment]
@BlackDex in the screenshot there is a response header
```
Grpc-Message: invalid gRPC request content-type "application/json"
```
It looks like the plugin might be configured to hit a gRPC service instead of HTTP? 

Maybe check the apiHost in your provisioning file.  The synthetic monitoring backend has a gRPC server as well as a HTTP server, and the URLs look very similar. For example in US east:
- gRPC: synthetic-monitoring-grpc-us-east-0.grafana.net:443
- HTTP: synthetic-monitoring-api-us-east-0.grafana.net

Please double check you are using the HTTP one and not gRPC

**Comment by BlackDex** [comment]
I probably have fully overlooked that multiple times. Ill check first thing tomorrow!

**Comment by BlackDex** [comment]
@peterschretlen Thanks, that solved the issue :).
